---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.servicename}}-pv
  namespace: {{ .Values.namespace}}
spec:
  capacity:
    storage: {{ .Values.pvsize}}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.volumehandle}}
