---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.servicename}}-pvc-claim
  namespace: {{ .Values.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.pvsize}}
  volumeName: {{ .Values.servicename}}-pv
