apiVersion: v1 
kind: Service 
metadata:
  name: {{ .Values.servicename}}
  namespace: {{ .Values.namespace}} 
spec:
  selector:
    app: tiotldap
  ports:
  - protocol: TCP
    port: 10391
    targetPort: 10391
  type: ClusterIP
